services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: teamlens
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql  # Hostname of the MySQL service
      PMA_USER: root
      PMA_PASSWORD: toor
    ports:
      - '8080:80'
    depends_on:
      - mysql

volumes:
  mysql_data:
