name: TeamLens - Live

on:
  push:
    branches:
      - main
    paths:
      - 'teamLens/**'
      - 'rmg/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.TEAMLENS_LIVE_URL }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.LIGHTSAIL_HOST }}
        username: ${{ vars.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          cd /home/ubuntu/TeamLens
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart teamlens