name: Google Sheet to CSV

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  convert-sheet-to-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas gspread google-auth google-auth-oauthlib google-auth-httplib2

      - name: Create Credentials File
        run: echo "$GOOGLE_CREDENTIALS" > creds.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Run Python Script to Convert Google Sheet to CSV
        run: python scripts/google_sheet_to_csv.py
        env:
          SHEET_ID: "${{ vars.GOOGLE_SHEET_ID }}"  # Change if needed
          SHEET_NAMES: "${{ vars.GOOGLE_SHEET_NAMES }}"  # Change if needed

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-sheet-csv
          path: "*.csv"

      - name: Clean up
        if: always()
        run: rm creds.json *.csv || true