# Generated by Django 5.1.7 on 2025-03-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmg', '0002_alter_profileupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdate',
            name='marked_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
