# Generated by Django 5.1.7 on 2025-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmg', '0004_alter_profileupdate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdate',
            name='comments',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
