# Generated by Django 5.1.7 on 2025-03-22 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmg', '0005_profileupdate_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_name', models.CharField(max_length=100)),
                ('requirement_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update')], max_length=10)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rmg.profileupdate')),
            ],
        ),
    ]
