# Generated by Django 5.1.7 on 2025-03-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmg', '0006_profileupdatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileupdatehistory',
            name='change_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10),
        ),
    ]
