# Generated by Django 5.1.7 on 2025-03-22 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmg', '0007_alter_profileupdatehistory_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
